DROP DATABASE IF EXISTS StudentPanel;

CREATE DATABASE IF NOT EXISTS StudentPanel;

USE StudentPanel;

CREATE TABLE IF NOT EXISTS Intent(
intentId INT AUTO_INCREMENT,
tag VARCHAR (255) NOT NULL,
answer VARCHAR (1000) NOT NULL,
media VARCHAR(45),
url VARCHAR(100),
PRIMARY KEY (intentId)
);

CREATE TABLE IF NOT EXISTS Keywords(
intentId INT NOT NULL,
keyword VARCHAR(255) NOT NULL,
FOREIGN KEY (intentId) REFERENCES Intent (intentId) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Insert tag and answers
INSERT INTO Intent (tag, answer, media, url) VALUES
('Professors, Advising, and Accessibility',
'Professors in introductory Engineering and Computational Sciences courses often have a big impact on students. They explain concepts clearly and encourage critical thinking and curiosity. Advising is very simple and easy. Everything is pretty straightforward and its pretty easy to get in contact with your advisors. Most professors and advisors are approachable and responsive, regularly meeting with students during office hours or over email. Many students say they wish they had reached out to professors sooner - faculty are approachable and eager to help.',
'', ''),
('Courses, Learning Style, and Capstone',
'Many Engineering and Computational Sciences courses are hands-on. Students regularly code and build projects, especially in advanced classes. Even theory-heavy courses tend to include practical components. Engineering and Computational Sciences seniors complete a semester-long capstone. Faculty propose project ideas, and students select one to develop and present.',
'image', '/media/Projects.jpg'),
('Industry Experience and Real-World Applications',
' Many professors have industry backgrounds and incorporate real-world examples and emerging technologies into their teaching.',
'', ''),
('Honors and Special Academic Opportunities',
'Yes, theres an Honors Program for students seeking deeper academic challenges. Independent research and advanced electives are also available.',
'', ''),
('Internships, Career Services, and Employment Outcomes',
'Engineering and Computational Sciences students intern at software companies, engineering firms, research labs, local startups, and major organizations like Raytheon and Microsoft. The OBrien Center provides personalized resume reviews, mock interviews, and career fairs. Faculty also support students with feedback and opportunity recommendations. Warriors at Work is a career development initiative from the OBrien Center. Students can apply and learn more through their website or staff. Graduates have gone on to organizations like Microsoft and MITRE, or continued their education at schools such as Northeastern and UMass Amherst.',
'', ''),
('Research, Publishing, and Summer Opportunities',
'Students can join ongoing faculty research or start independent projects. Those who contribute meaningfully often co-author publications. Students can work with faculty on research over the summer, sometimes with stipends.',
'image', '/media/Research.jpg'),
('Academic Support and Class Sizes',
'Engineering and Computational Sciences classes are typically small - around 15-25 students - allowing for more direct support and interaction with faculty. Tutoring is available through the Math Center and Peer Tutoring, especially for challenging courses like Data Structures and Circuits.',
'image', '/media/Class_Size.jpeg'),
('Lab Access and Facilities',
' Most labs and makerspaces remain open in the evenings and on weekends, and students can access them with their Mack Cards. Engineering and Computational Sciences facilities include modern labs, a robotics lab, and a makerspace equipped with 3D printers and other tools.',
'image', '/media/Lab_Hours.jpg'),
('Collaboration Across Majors',
' Collaboration between CS and Engineering students is common, especially in research and clubs that combine coding and hardware. Interdisciplinary collaboration happens through innovation challenges, joint classes, and service projects across schools.',
'', ''),
('Clubs, Leadership, and Competitions',
'Clubs include SWE, Robotics, NSBE, Lets Innovate, the Computer Club, and others focused on tech and engineering interests. Most clubs meet weekly and are considerate of academic demands, helping students manage both involvement and schoolwork effectively. Merrimack hosts some events, and students also attend hackathons at nearby institutions for hands-on experience and networking. Students can take on leadership roles in clubs, guide team projects, or serve as peer mentors and tutors.',
'image', '/media/Clubs.jpg'),
('Undecided Engineering',
'Undecided Engineering students take general courses that apply across majors. Advisors help them explore interests before choosing a specific path.',
'', ''),
('Campus Logistics - Transportation, Housing, Dining',
'Most Engineering and Computational Sciences students walk or use the campus shuttle to travel between buildings. Most Engineering and Computational Sciences classes are held on the east side, while general education classes are typically located on the main campus. Housing is available on campus for all years, and off-campus apartments are located nearby for upperclassmen. Engineering and Computational Sciences students can eat at a smaller dining location on the Engineering and Computational Sciences side or at a food truck during warmer months, both accepting meal swipes.',
'image', '/media/Warrior_Shuttle.jpg'),
('Studying Habits and Community',
'Popular study spots include the second-floor lounge in the Engineering and Computational Sciences building, which is conveniently close to faculty offices. It varies. Many students study in groups for projects, while others prefer studying independently. The Engineering and Computational Sciences community is tight-knit and supportive. Students help one another, and faculty are genuinely invested in student success.',
'', ''),
('Programming, Tools, and Projects',
'Students typically learn Java, Python, SQL, and sometimes JavaScript or C/C++, depending on the electives taken. Courses use tools like VSCode, GitHub, MATLAB, and more. Most instructors allow students to use any IDE as long as the work is completed correctly. Students are encouraged to build GitHub portfolios and some contribute to the colleges open-source utilities.',
'', ''),
('Cultural Adaptation and Support for Underrepresented Students',
'There are orientation programs, and the campus community is generally welcoming and eager to learn about different cultures and experiences. Programs like Compass and mentoring initiatives through academic departments and the OBrien Center support underrepresented students.',
'image', '/media/Breaking_Bread.jpg'),
('Study Abroad and Service Trips',
' Students can study abroad during the summer or semester, and some Engineering and Computational Sciences students participate in engineering service trips through the SEND Program. The SEND Program offers service trips during breaks where students volunteer in U.S. and international communities, focusing on social justice and personal growth.',
'image', '/media/Study_Abroad.jpeg'),
('Financial Info and Enrollment',
'Tuition is managed through the Bursars Office, and students can set up payment plans through the college portal. Students can contact the Financial Aid Office or visit the Merrimack website under Scholarships & Aid. Deposits are made through the Admissions Portal. The Admissions Office on the main campus is available to assist if needed.',
'image', '/media/Warrior_One_Stop.jpg'),
('Student Life - Challenges, Reasons for Choosing Merrimack, and Favorite Aspects',
'Balancing coursework and managing time is often a challenge at first, but support systems are in place to help. Students often cite small class sizes, early research opportunities, and a strong support system as key reasons. The strong sense of community. Students appreciate being recognized and having close connections with professors and peers.',
'', ''),
('First-Year Experience and Transition Support',
'First-year Engineering and Computational Sciences students have access to special programs like the First-Year Experience (FYE) course, which helps with academic skills, career planning, and adjusting to college life. Peer mentors and orientation leaders are available to guide students during their transition. Faculty advisors are also assigned early on to help plan course schedules and answer questions.',
'', ''),
('Health, Wellness, and Counseling Services',
'The Hamel Health Center offers medical services, counseling, and wellness programming. Students can schedule appointments for physical and mental health services. Counseling support is free, and the college regularly hosts events promoting mental well-being, like stress relief days and therapy dog visits.',
'image', '/media/Hamel_Health.jpg'),
('Typical Day and Class Schedules',
'A typical day might include a mix of lectures, lab sessions, and study blocks. Engineering and Computational Sciences classes usually run between 8:00 AM and 6:00 PM, with gaps for meals, studying, and club meetings. Labs are often scheduled in the afternoons and can last a few hours. Students usually balance classes, homework, group meetings, and time to relax.',
'', ''),
('Scholarships and Merit Awards',
'Merrimack automatically considers admitted students for merit scholarships based on academic achievements. Additional scholarships may be available based on financial need, special interests, or participation in programs like Honors. Students can also apply for external scholarships and research assistantships once enrolled.',
'', ''),
('Athletics, Fitness, and Recreation',
'Students have access to the Merrimack Athletics Complex (MAC), fitness classes, club sports, and intramural leagues. There is a large gym, indoor track, pool, and courts available. Even non-athletes can join fitness classes like yoga, Zumba, or lifting programs.',
'image', '/media/MAC.png'),
('Weather and Seasonal Life on Campus',
'Merrimack experiences all four seasons. Fall is beautiful with colorful leaves, winters can bring snow and cold temperatures, spring brings mild weather and flowers, and summers are warm. Students typically layer up in winter and take advantage of indoor study spaces. Snow events are handled efficiently, and the campus community stays active all year.',
'', ''),
('Making Friends and Getting Involved',
'Joining clubs, participating in Welcome Week events, and living on campus are some of the easiest ways to make friends. Many students meet people through classes, shared study spaces, and group projects. The college encourages involvement and offers leadership workshops and social events year-round.',
'image', '/media/Clubs.jpg'),
('Weekend Life and Local Area',
'On weekends, students often attend campus events, participate in club activities, study, or explore the surrounding area. Merrimack is close to Boston, beaches, and hiking trails. Students can take campus shuttles, carpool, or use the commuter rail to go into the city. The local area also offers shopping, restaurants, and entertainment.',
'', ''),
('Housing Options and Roommate Matching',
'First-year students typically live in residence halls with roommates assigned based on a questionnaire about living habits. Upperclassmen can live in suites, apartments, or off-campus housing nearby. There are Living Learning Communities (LLCs) for students who want to live with peers who share similar interests.',
'image', '/media/Dorm.jpg'),
('Time Management and Balancing Activities',
'Engineering and Computational Sciences students often find success by using planners, scheduling their study time, and setting priorities early on. Professors understand that students are involved in multiple activities and encourage communication if conflicts arise. Campus resources like the Academic Success Center offer time management workshops.',
'', ''),
('Commuter Life and Resources',
'Commuters are a big part of the Merrimack community. There are commuter lounges on campus where students can study, relax, and store personal items. Commuters often stay involved through clubs, events, and academic support programs. Parking permits are available and the shuttle system makes getting around campus easy.',
'image', '/media/Commuter.png'),
('General Student Clubs and Organizations',
'Merrimack offers more than just academic clubs - there are social clubs, cultural organizations, service groups, and recreational clubs. From theater productions and dance teams to business clubs and gaming groups, there is something for everyone. Students are encouraged to explore and join multiple groups.',
'image', '/media/Clubs.jpg'),
('Campus-Wide Events and Traditions',
'Merrimack hosts many fun traditions throughout the year, like Homecoming, Macktoberfest, Springapalooza, and Midnight Madness. Events usually feature free food, games, and activities. Both commuters and residents get involved. There are also guest speakers, concerts, and charity events.',
'image', '/media/Homecoming.jpg'),
('Eating on Campus (Lunch and Casual Dining)',
'Besides the main dining hall, students often grab food from Sparkys Place, The Warriors Den, Dunkin, or food trucks on campus. Meal plans cover most locations, and points can be used for extra flexibility. There are spots to eat near both the Engineering side and the main campus.',
'image', '/media/Sparkys.png'),
('School Spirit, Athletics, and Game Attendance',
'Even if you arent an athlete, going to games is a big part of campus life. Hockey games at Lawler Arena are especially popular and often free or discounted for students. Merrimack has Division One sports teams, and many students attend games together to support the Warriors.',
'image', '/media/Hockey.png'),
('Involvement for New Students (Finding Your Place)',
'It can seem overwhelming at first, but new students quickly find their place. Welcome Week activities, club fairs, and social events are designed to help everyone connect. Joining even one club or attending a few events makes it much easier to make friends and get comfortable.',
'', ''),
('Merrimack College Look and Feel',
"Merrimack College has a beautiful campus with a classic New England feel. You'll find tree-lined paths, modern academic buildings, open green spaces, and cozy spots to study. The architecture is a blend of traditional brick and newer contemporary designs. In the fall, the campus is especially stunning with colorful foliage.",
'video', '/media/Video.mp4');


-- Insert keywords
INSERT INTO Keywords (intentId, keyword) VALUES
(1, 'professors'), (1, 'faculty'), (1, 'advising'), (1, 'advisor meetings'), (1, 'accessibility'), (1, 'office hours'), (1, 'email responses'), (1, 'faculty meetings'), (1, 'professor availability'), (1, 'academic advising'), (1, 'advisor appointments'), (1, 'meet with advisors'),
(2, 'hands-on courses'), (2, 'project-based learning'), (2, 'coding projects'), (2, 'labs and builds'), (2, 'capstone project'), (2, 'semester project'), (2, 'project-oriented classes'), (2, 'team-based learning'), (2, 'classroom projects'), (2, 'hands-on labs'),
(3, 'industry experience'), (3, 'real world examples'), (3, 'emerging technologies'), (3, 'practical applications'), (3, 'industry-connected faculty'), (3, 'internship programs'), (3, 'industry partnerships'), (3, 'corporate connections'), (3, 'practical training'), (3, 'real world techniques'),
(4, 'honors program'), (4, 'advanced electives'), (4, 'independent research'), (4, 'academic challenges'), (4, 'research opportunities'), (4, 'scholarship opportunities'), (4, 'graduate-level electives'), (4, 'research funding'), (4, 'specialized courses'),
(5, 'internships'), (5, 'career services'), (5, 'Warriors at Work'), (5, 'resume help'), (5, 'mock interviews'), (5, 'career fairs'), (5, 'graduate schools'), (5, 'job placement'), (5, 'job search support'), (5, 'career guidance'), (5, 'resume building workshops'), (5, 'job preparation resources'), (5, 'internship'),
(6, 'student research'), (6, 'faculty research'), (6, 'summer stipends'), (6, 'co-author publications'), (6, 'research collaboration'), (6, 'academic publications'), (6, 'faculty collaboration'), (6, 'student publications'), (6, 'research conferences'),
(7, 'small class sizes'), (7, 'academic support'), (7, 'peer tutoring'), (7, 'math center'), (7, 'one-on-one help'), (7, 'individualized instruction'), (7, 'student-faculty ratio'), (7, 'learning resources'), (7, 'faculty-student engagement'), (7, 'peer tutors'),
(8, 'labs'), (8, 'makerspaces'), (8, 'robotics lab'), (8, '3D printers'), (8, 'Mack Card access'), (8, 'lab hours'), (8, 'research projects'), (8, 'tech labs'), (8, 'engineering workshops'), (8, 'design studios'), (8, 'available facilities'),
(9, 'CS and Engineering collaboration'), (9, 'interdisciplinary projects'), (9, 'joint classes'), (9, 'innovation challenges'), (9, 'service projects'), (9, 'cross-disciplinary learning'), (9, 'joint projects with engineering'), (9, 'innovation labs'), (9, 'tech challenges'),
(10, 'clubs'), (10, 'hackathons'), (10, 'student leadership'), (10, 'club meetings'), (10, 'technical clubs'), (10, 'peer mentoring'), (10, 'coding competitions'), (10, 'tech meetups'), (10, 'club participation'), (10, 'volunteer opportunities'),
(11, 'undecided engineering students'), (11, 'advisors'), (11, 'general engineering courses'), (11, 'major exploration'), (11, 'undecided major'), (11, 'general engineering courses'), (11, 'exploring career paths'), (11, 'major transition support'),
(12, 'transportation'), (12, 'campus shuttle'), (12, 'housing'), (12, 'on-campus living'), (12, 'off-campus apartments'), (12, 'dining options'), (12, 'meal swipes'), (12, 'on-campus housing'), (12, 'commuting options'), (12, 'meal plan options'), (12, 'campus living facilities'),
(13, 'study spots'), (13, 'second floor lounge'), (13, 'community support'), (13, 'group study'), (13, 'independent study'), (13, 'tight-knit community'), (13, 'study lounges'), (13, 'quiet study areas'), (13, 'library spaces'), (13, 'collaborative study spaces'), (13, 'hidden spots'),
(14, 'programming languages'), (14, 'Java'), (14, 'Python'), (14, 'SQL'), (14, 'software tools'), (14, 'VSCode'), (14, 'GitHub'), (14, 'open-source projects'), (14, 'C++ programming'), (14, 'JavaScript'), (14, 'R programming'), (14, 'programming assignments'), (14, 'coding environments'),
(15, 'international students'), (15, 'underrepresented students'), (15, 'Compass program'), (15, 'diversity support'), (15, 'mentoring initiatives'), (15, 'cultural inclusion'), (15, 'student organizations for diversity'), (15, 'support for minorities'), (15, 'multicultural events'), (15, 'other cultures'),
(16, 'study abroad'), (16, 'SEND Program'), (16, 'service trips'), (16, 'engineering service trips'), (16, 'summer abroad'), (16, 'volunteer trips'), (16, 'service-learning experiences'), (16, 'global internships'), (16, 'travel abroad experiences'),
(17, 'tuition payment'), (17, 'payment plans'), (17, 'scholarships'), (17, 'financial aid'), (17, 'deposit process'), (17, 'bursar office'), (17, 'financial aid application'), (17, 'tuition assistance'), (17, 'student loans'), (17, 'financial workshops'),
(18, 'student life'), (18, 'balancing coursework'), (18, 'challenges'), (18, 'reasons for choosing Merrimack'), (18, 'favorite aspects'), (18, 'close community'), (18, 'student organizations'), (18, 'leadership roles in clubs'), (18, 'community involvement'), (18, 'student volunteerism'), (18, 'balance homework'),
(19, 'first year experience'), (19, 'transition support'), (19, 'FYE course'), (19, 'peer mentors'), (19, 'orientation leaders'), (19, 'academic advisors'), (19, 'mentorship programs'), (19, 'peer advisor programs'), (19, 'first year success'), (19, 'upperclassmen mentors'),
(20, 'health services'), (20, 'wellness programs'), (20, 'counseling services'), (20, 'mental health support'), (20, 'Hamel Health Center'), (20, 'therapy dogs'), (20, 'physical health programs'), (20, 'counseling resources'), (20, 'support for anxiety'), (20, 'health and wellness events'), (20, 'mental help'), (20, 'mental issues'),
(21, 'daily schedule'), (21, 'class times'), (21, 'typical day'), (21, 'lab sessions'), (21, 'study blocks'), (21, 'academic life'), (21, 'class schedules'), (21, 'classroom hours'), (21, 'free time in between classes'), (21, 'workshops and seminars'), (21, 'average day'),
(22, 'merit scholarships'), (22, 'financial awards'), (22, 'academic scholarships'), (22, 'external scholarships'), (22, 'honors scholarships'), (22, 'scholarship deadlines'), (22, 'external funding opportunities'), (22, 'scholarship eligibility'), (22, 'financial aid deadlines'),
(23, 'athletics'), (23, 'fitness center'), (23, 'MAC'), (23, 'club sports'), (23, 'intramurals'), (23, 'group fitness classes'), (23, 'sports teams'), (23, 'fitness challenges'), (23, 'gym facilities'), (23, 'wellness programs'),
(24, 'seasonal life'), (24, 'weather on campus'), (24, 'snow and winter'), (24, 'fall foliage'), (24, 'spring and summer'), (24, 'local weather patterns'), (24, 'campus events calendar'), (24, 'seasonal festivals'), (24, 'holiday celebrations'),
(25, 'making friends'), (25, 'getting involved'), (25, 'welcome week'), (25, 'student organizations'), (25, 'leadership workshops'), (25, 'social activities'), (25, 'making connections'), (25, 'club involvement'), (25, 'team-building activities'),
(26, 'weekend activities'), (26, 'local area'), (26, 'Boston trips'), (26, 'campus events'), (26, 'off-campus exploration'), (26, 'weekend getaways'), (26, 'local hikes'), (26, 'weekend events'), (26, 'community outings'),
(27, 'housing options'), (27, 'roommate matching'), (27, 'first-year housing'), (27, 'living learning communities'), (27, 'residence halls'), (27, 'housing applications'), (27, 'room assignments'), (27, 'residence hall activities'), (27, 'apartment tours'),
(28, 'time management'), (28, 'balancing academics'), (28, 'study skills'), (28, 'academic success center'), (28, 'priority setting'), (28, 'study resources'), (28, 'academic workshops'), (28, 'study schedules'), (28, 'peer tutoring'),(28, 'social and academic balance'),
(29, 'commuters'), (29, 'commuter lounge'), (29, 'parking permits'), (29, 'campus shuttle'), (29, 'commuter involvement'), (29, 'commuting options for students'), (29, 'commuter students events'), (29, 'commuter study space'), (29, 'parking access'),
(30, 'student clubs'), (30, 'social organizations'), (30, 'cultural clubs'), (30, 'service groups'), (30, 'recreational clubs'), (30, 'cultural diversity in clubs'), (30, 'student-led initiatives'), (30, 'group activities'), (30, 'recreational events'), (30, 'nonformal clubs'), (30, 'fun clubs'),
(31, 'campus traditions'), (31, 'homecoming'), (31, 'Macktoberfest'), (31, 'springapalooza'), (31, 'midnight madness'), (31, 'campus events'), (31, 'Merrimack traditions'), (31, 'Merrimack festivals'), (31, 'community gatherings'), (31, 'annual events'),(31, 'fun events'),
(32, 'dining options'), (32, 'sparkys place'), (32, 'warriors den'), (32, 'dunkin on campus'), (32, 'food trucks'), (32, 'meal plan points'), (32, 'campus eateries'), (32, 'on-campus dining'), (32, 'healthy food options'), (32, 'meal preferences'),
(33, 'school spirit'), (33, 'attending games'), (33, 'hockey games'), (33, 'division one sports'), (33, 'lawler arena'), (33, 'athletic events'), (33, 'attending athletic events'), (33, 'sports team support'), (33, 'spirit events'), (33, 'school sports'),
(34, 'getting involved'), (34, 'welcome week'), (34, 'club fair'), (34, 'making friends'), (34, 'new student adjustment'), (34, 'student welcome programs'), (34, 'getting acquainted with campus'), (34, 'orientation activities'), (34, 'student meetups'), (34, 'first year experience'),
(35, 'what does Merrimack look like'), (35, 'campus appearance'), (35, 'campus look'), (35, 'Merrimack College campus'), (35, 'Merrimack architecture'), (35, 'Merrimack atmosphere'), (35, 'campus scenery'), (35, 'Merrimack College vibe'), (35, 'college look and feel'), (35, 'how does the campus look'), (35, 'describe Merrimack'), (35, 'is Merrimack a pretty campus'), (35, 'how beautiful is Merrimack'), (35, 'how nice is the campus');
